Sprint 2
MihailFirsov/middle.messenger.praktikum.yandex pull request #2
Opened 2021-06-22 20:07 UTC by MihailFirsov

2021-06-23 15:44 UTC, nickchamel requested changes
Привет. Работа хорошая! Но есть несколько замечаний. Описал ниже в комментариях

2021-06-23 15:44 UTC, nickchamel commented on src/components/button/button.ts
> +    }
Жесткая привязка слоев приложения. Представь если проект развивается, пилятся новые фичи, меняется дизайн, верстка и вот поменяли название класс в шаблоне и у тебя из-за этого приложение перестало работать. 
Незачем вообще делать классы динамическими. У тебя сделано так что при создании компонента ты прокидываешь класс через пропсы. А если я от балды напишу любой класс? То верстка поедет...
Классы просто должны быть статичными и быть объявлены в шаблонах и все.
Единственное исключение, это когда валидацию делаешь, если в инпуте невалидное значение, то на этот инпут нужно добавить класс `.error` например.

2021-06-23 15:44 UTC, nickchamel commented on src/components/button/button.ts
> +    }
Не совсем понял зачем ты вообще сделал preparedTmpl) У тебя ведь pug и он позволяет ререндерить один и тот же шаблон с разными локалями. То есть например `return compile(tmpl)(this.props);` и в шаблоне пишешь переменные как собственно в pug-шаблонах они и пишутся. А ты получается сделал некое подобие своего парсера над pug. То есть я хочу сказать, что это попросту излишне, но если тебе так нравится то ок, можешь не менять этого!

2021-06-23 15:44 UTC, nickchamel commented on src/components/chat/components/chat-list-controls/chat-list-controls.tmpl.ts
> +    a.chat-list-controls__profile(onclick="window.renderPage('profile')") Профиль
Насколько я понял, ты решил забежать вперед и сделать некое подобие роутера, он конечно не совсем так работает, но можно пока оставить и так до 3 спринта. Как минимум у тебя сейчас получилось так, что при переходах урл никогда не меняется

2021-06-23 15:44 UTC, nickchamel commented on src/components/chat/components/chat-message-list/chat-message-list.ts
> +import {ComponentProps} from '../../../../types/component';
Тип пропсов компонента лучше держать в самой папке компонента.
`src/components/chat/components/chat-message-list/chat-message-list.types.ts`
Или просто в файле самого компонента
В этом и суть модуля. У тебя есть готовые компонент, который ты можешь взять и переиспользовать, даже между разными проектами.
Плюс все всегда "под рукой" когда делаешь изменения в каком-либо компоненте

2021-06-23 15:44 UTC, nickchamel commented on src/components/chat/components/chat-profile/chat-profile.ts
> +    }
Вообще для таких действий вроде как и есть метод componentDidMount. Но это не суть, а суть в том, что тут опять же привязка к шаблону. Лучше избегать использование имен классов здесь.
Можно вешать все события на this.node например а в коллбэках уже смотреть какой элемент в таргете находится (по tagName)
Можно делать некоторое подобие рефов как в реакте, то есть при парсинге шаблона если у элемента есть атрибут реф, скажем `ref="popoverBtn"`, то делать собственно ссылку на этот элемент и после рендера здесь он будет доступен например `this.refs.popoverBtn`.
Так ты избавишься от привязки слоев.
А модалка по идее должны быть синглтоном. Здесь ее можно имортнуть и вызвать у нее методы показать/скрыть.
Подумай над вариантами, по хорошему от привязки нужно избавляться

2021-06-23 15:44 UTC, nickchamel commented on src/components/component/component.ts
> +        this.eventBus = () => eventBus;
Можно просто `this.eventBus = new EventBus();`

2021-06-23 15:44 UTC, nickchamel commented on src/components/component/component.ts
> +    }
Вот у тебя кстати метод который вешает события на корневую ноду, правда достаточно вешать на this.node

2021-06-23 15:44 UTC, nickchamel commented on src/pages/sign-up/sign-up.ts
> +    }
Чтобы выдержать один стиль, было бы неплохо вынести шаблон в файл

2021-06-23 15:44 UTC, nickchamel commented on src/pages/sign-up/sign-up.ts
> +    }
Опять же нужно избегать селекторов здесь. Нужно сделать ивенты либо через корневую ноду, либо через ссылки на дочерние элементы. Кстати я не заметил, что в консоли что-то выводило при сабмите форм. Я имею ввиду данные. Это по заданию нужно сделать. И валидация - я тоже не вижу чтобы она работатала

2021-06-23 15:44 UTC, nickchamel commented on src/utils/validate.ts
> +};
Такие хэлперы должны быть максимально простыми, незачем сюда прокидывать компонент. Лушче в компоненте, там где вешаем события, написать логику которая будет вызывать эту функцию и возвращать true/false

2021-06-24 10:14 UTC, MihailFirsov commented on src/pages/sign-up/sign-up.ts
> +    }
Сделал через refs. Валидация да, реактивность потерялась. Поправил и в консоль данные с формы приходят

2021-06-24 10:14 UTC, MihailFirsov commented on src/utils/validate.ts
> +};
++

2021-06-24 13:08 UTC, nickchamel approved these changes
> Что-то я тут не очень согласен - если передаешь в свойстве classname от балды, то просто добавится в .btn дополнительный класс. Это наоборот удобно, если нужны свои отступы кнопке добавить, чтобы не патчить .btn

Я имею ввиду, что сам компонент не должен "оперировать" именами классов - это не его область отвественности. Если мы говорим о кнопке то у нее должны быть пропса - например `theme` которую можно использовать при создании компонента
```
const submit = new Button({
  ...
  theme: 'blue',
  ...
});
```
заместо `className: 'btn_blue'`. А уже в шаблоне в зависимости от темы можешь вывести определенный класс. Если хочешь ты можешь даже в шаблоне использовать либу classnames, просто прокидывая ее в локали) К тому же такую пропсу можно хорошо типизировать например `ThemeType = 'blue' | 'green'`

Вообщем это тебе рекомендация, сейчас это точно не критично, работу я принимаю, хорошо поработал, молодец. Удачи в дальнейшем!
Еще кстати проверь регулярку на емейл - она у тебя выдает валидный на `qwe@q`

2021-08-21 09:54 UTC, merged